### ISSUE TITLE
Chat-invitations

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#1]
> invite user to one of your chats by name click

**Comment by Idrinth** [comment]
Just wondering if invitation without the need of agreeing would be sufficient, @w20k  - that would make sure i don't need a whisper-like system first.

**Comment by w20k** [comment]
I think it could work, but you should have visual notification - popup, that you've been added to a group with "Name". 
Chat flickering, does not providing you with proper info right now.

**Comment by Idrinth** [comment]
Added https://dotd.idrinth.de/kongregate/chat-service/my-chats/ as a service returning the same set of data login does, so rechecking is cheaper and quicker

**Comment by Idrinth** [comment]
With the invites being handled like promotions, this would be fine in #36 - works the same then, a person who is not banned sends a request to set another user's rank to "User" in that chat. <Do you want to integrate that in the task you picked, @w20k ?

**Comment by w20k** [comment]
I think better to make another small task. Easier to track down issues.
I already finished with basics :)
