### ISSUE TITLE
Provide tests to be run on Commits

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#125]
Following #65 we agreed upon creating tests for the code to prevent us from stupid mistakes in the furture.
The setup provided is nodejs v4.4.7 with [jasmine ](https://github.com/jasmine/)2.4.1, those versions may be updated soon.

When deploying, the tests will have the complete javascript file included in their main folder with the name idotd.js .

**Comment by w20k** [comment]
It's should be done from server side as well partially? Or you already made some script runner command like npm test or something?

**Comment by w20k** [comment]
Will take this one.

**Comment by Idrinth** [comment]
thanks :) I hate writing tests, but love using them :D
There is not yet anything there but the php-code to call a function. The number of files to be run shouldn't matter much, I'm mostly done with the change to a json-configuration, that will allow multiple tests to be run.

**Comment by w20k** [comment]
That sounds good! Will start with this one on the week ;)

**Comment by w20k** [comment]
@Idrinth , what should be done from server side to make test running? :) Do we need coverage report ? ;) 
If you would like, just take a look at my branch. 
Running tests - "npm test", before that "npm install".

**Comment by Idrinth** [comment]
coverage reports could be pretty useful in a while - I mean this is not something that will be done today.

Need finally find the time to finish the new version(or fix the last broken bits) of the auto-release script to have the tests running. Hope to find time later today.

**Comment by w20k** [comment]
@Idrinth , good than. Will start doing test, and if you have time. Just take a look - everything in place already (core part).

**Comment by Idrinth** [comment]
you mentioned wanting to switch to chai (http://chaijs.com/) or mocha(https://github.com/mochajs/mocha), any update on the choices or are you planning on using both, @w20k ?
The one they use in their docs is not chai, that's why I'm wondering.

**Comment by Idrinth** [comment]
```yaml
language: node_js
node_js: "node"
git:
  depth: 3
before_script:
  - npm install chai
  - npm install mocha
script:
  - ./node_modules/.bin/mocha --reporter spec
````
should be sufficient for a .travis.yml, just consider it untested

**Comment by w20k** [comment]
Chai & Mocha :) It's like mochachai, already started, but not often right now. 
Okey, will test it on weekends, probably ;)

@Idrinth, thanks )

**Comment by Idrinth** [comment]
https://travis-ci.org/Yet-Another-Web-Stack/CrossUserEvents-Javascript-Websocket played a bit around with this, actually found an error that way - feel free to have a look at the configuration.

**Comment by w20k** [comment]
@Idrinth  thanks ;)
