### ISSUE TITLE
first run tutorial?

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#129]
I'm wondering if a kind of first-run tutorial would be helpful - like pointing out what the elements are.
Obviously this should be a file of it's own, only loaded if a specific boolean (as in ran before) is set.

**Comment by w20k** [comment]
Is it really needed? I mean there is not that much functionality. Plus it's better to deal with a proper UI :)

**Comment by Idrinth** [comment]
Not sure, just an idea. Improving the UI is certainly more important both in the short and the long run.

Came up with that, since I just helped someone on facebook to get it up and running.

**Comment by Idrinth** [comment]
guess it's not interesting
