### ISSUE TITLE
Java(script) docs

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#135]
Add java-doc like comment blocks to all (public) methods and properties to make it easier to handle them.
https://yui.github.io/yuidoc/ gives an example.

**Comment by w20k** [comment]
Yeah, would be quite useful :) We could generate docs after that.
Like this or any other:
https://github.com/lord/slate

**Comment by Idrinth** [comment]
Had a talk with @Algareb about this yesterday, he's likely to start on this, since he's just working on understanding the code.

**Comment by Idrinth** [comment]
@w20k what about https://github.com/jsdoc3/jsdoc instead of slate? we got a nodejs up and running already after all :)

**Comment by w20k** [comment]
Jsdoc is quite good ;) Take it if you have some spare minutes :)

**Comment by Idrinth** [comment]
JSDoc is currently not working the way we expected, https://doclets.io/IDotD/Userscript/master would be an example for the output.
Does anyone have a better, compatible idea, @IDotD/javascript

**Comment by Idrinth** [comment]
missing modules:
- chat
- land
- raids

**Comment by Idrinth** [comment]
missing modules:
* chat
* land
