### ISSUE TITLE
Remove  clipboard.js

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#137]
Replace clipboard.js with the given functionality in idrinth.core to reduce the total size of the script.

**Comment by w20k** [comment]
Should be an easy task, after all your effort ;) Thanks mate!

**Comment by Idrinth** [comment]
yw, most of it was reading up on how to handle copiing - actually interesting :) we could skip a lot of horrible parts thanks to our more limited range of browsers.
