### ISSUE TITLE
Do we want a CSS-preprocessor?

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#143]
I'm just wondering, if there might be use for a preprocessor once we cleaned up the current css in #142 . That might be especially useful, once you, @w20k , start on the redesign you planned on doing in the beginning ;)

**Comment by Idrinth** [comment]
https://csspre.com/compare/ just as a resource, I'm sure there's some more

**Comment by w20k** [comment]
Or we could use something like this. If we tend to have complex structure.
https://github.com/tachyons-css/tachyons

I will, next month probably, still on business trips, for few more weeks ;(

**Comment by Idrinth** [comment]
My idea was mostly about making the actual css easier to read - we do have a lot of gui elements for a script this small, so anything we can live without should help a lot in maintaining it.

tachyons seems to be overkill here, after we aren't building a complete website and merely a few modules for it.

**Comment by w20k** [comment]
It depends how you use it (tachyons - could be just headers or skeleton). But you state it this way, I'd use SCSS (it's my preference). For small projects there is no big difference in thouse :)

**Comment by Idrinth** [comment]
we got a few implementations in any case, just a quick look gave me the following one as the most commonly used basis for others:
https://github.com/leafo/scssphp

Not sure if I'd consider that stable judging from the issues it has listed, but well, neither is our code here.

**Comment by Idrinth** [comment]
@w20k since you're starting on the style changes, would SCSS  help you? Could easily add it to a api-call.

**Comment by w20k** [comment]
@Idrinth  - Would be great - do it ;)

**Comment by Idrinth** [comment]
https://dotd.idrinth.de/kongregate/userscript-styles/[branch]/ should now provide the parsed contents of a root.scss in /src - minification for the master obviously, works pretty much the same as the userscript-page.

hope that works, @w20k

**Comment by w20k** [comment]
Much appreciated @Idrinth  ;)

**Comment by Idrinth** [comment]
we are using leafo's implementation, the one linked above, should work fine with imports as well if necessary :)
