### ISSUE TITLE
Newgrounds: List of raids not being filled

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#144]
currently the list of raids to join on newgrounds is not being filled with raids.
The request to the server returns raids as expected.

**Comment by Idrinth** [comment]
@w20k could you have a look at that? it's breaking he core functionality there and I lack the time to fix it atm :/

**Comment by w20k** [comment]
Will take a look, though don't have Newgrounds account, but it's fixable :)

**Comment by Idrinth** [comment]
I think it just does a pseudo-join and then hides the raids

**Comment by w20k** [comment]
Could you write down exactly what is not working? Raid list is showing for me correctly. I'm not sure what is wrong than?

Tested like 2mins ago ;)

Could you write down steps to reproduce? As short as possible.

The only thing it does not - is joining to raids that's have been added to the list. That's the only thing for now.

**Comment by Idrinth** [comment]
not joining is sadly the normal thing there - no way of automatically doing that besides reloading the game every time.
Will retest again later, maybe just had weird interference with the site itself.

**Comment by Idrinth** [comment]
no idea why it didn't work before, have been unable to replicate the issue - sorry about that

**Comment by w20k** [comment]
No worries, that's why issue tracking system was made for :)
