### ISSUE TITLE
Add campaign data

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#147]
> Add both the tiers as well as the map and a list of the modifiers(challenge, prefix) to the userscript.

Was asked about that a few times, mostly useful for mutik-less servers.

**Comment by Theodotosp** [comment]
We have some campaign raids that will be covered in the #148 issue. The rest data how can be uploaded? Idrinth you have to make changes? The name arent in the file.

**Comment by Idrinth** [comment]
camps will have their own structure, didn't intend to add campaign nodes to the normal tier list - just ignore them please :)

**Comment by Idrinth** [comment]
@Theodotosp https://github.com/Idrinth/IDotD/commit/b2bda532029530e959eba7d7baf2f9cc2fabe7a4 is what I currently intend for the structure, with the node's tiers following the tiers we have for raids in the way they're structured.

Do you think that's sufficient?

**Comment by Theodotosp** [comment]
I think that it is very satisfing how it is right now. As soon as i finish with tiers data will procide to that.

**Comment by Idrinth** [comment]
ty :)

**Comment by Idrinth** [comment]
tinyurl.com/hsl6v6e

**Comment by Idrinth** [comment]
moved to https://github.com/IDotD/Campaigns/issues
