### ISSUE TITLE
Add missing tier data

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#148]
In best case as  a simple json: difficulty -> damage -> epics, just attached here.

Missing bosses atm: https://dotd.idrinth.de/static/missing-tiers/

This is not meant to gather new tiers, just collect the already existing data. The official forums and the wiki might be a good source.

**Comment by Idrinth** [comment]
Hargamesh example:

```
{
    "normal":{
        "945000":1,
        "1080000":1,
        "1620000":1,
        "2160000":2,
        "2880000":2.5,
        "4500000":3,
        "6300000":3.5
    },
    "hard":{
        "1181000":1,
        "1350000":1,
        "2025000":1,
        "2700000":2,
        "3600000":2.5,
        "5625000":3,
        "7875000":3.5
    },
    "legendary":{
        "1512000":1,
        "1728000":1,
        "2592000":1,
        "3456000":2,
        "4608000":2.5,
        "7200000":3,
        "1008000":3.5
    },
    "nightmare":{
        "1890000":1,
        "2160000":1,
        "3240000":1,
        "4320000":2,
        "5760000":2.5,
        "9000000":3,
        "12600000":3.5
    }
}
```

**Comment by Theodotosp** [comment]
"Elite Balor":
{
"nightmare":{
        "50000000":2840,
        "75000000":5165,
        "80000000":5570,
        "100000000":7000,
        "125000000":8800,
        "150000000":9100,
        "180000000":9100,
        "200000000":10100,
        "250000000":10600,
        "300000000":11600,
        "350000000":11600,
        "400000000":12100,
        "500000000":12600
    }
}

**Comment by Theodotosp** [comment]
"Balor":
{
"nightmare":{
"8000000":395,
"10000000":801,
"35000000":1354,
"50000000":1891,
"100000000":3304,
"150000000":3554,
"200000000":4006
}
}

**Comment by Theodotosp** [comment]
"Elite Kanehuar Yachu":
{
"nightmare":{
"25000000":1260,
"36700000":1930,
"40000000":2230,
"45000000":2530,
"50000000":2830,
"55000000":3130,
"60000000":3950,
"65000000":4350,
"73300000":4750,
"75000000":5150,
"80000000":5550,
"90000000":6250,
"100000000":6950,
"125000000":8700,
"180000000":9000,
"200000000":10000,
"250000000":10500,
"350000000":11500,
"400000000":12000
}
}

**Comment by Theodotosp** [comment]
"Chieftain Horgrak":
{
    "normal":{
        "8000":1,
        "9000":1,
        "14000":1,
        "18000":2,
        "24000":2.5,
        "38000":3,
        "53000":3.5
    }
    "hard":{
        "10000":1,
        "11000":1,
        "17000":1,
        "23000":2,
        "30000":2.5,
        "47000":3,
        "66000":3.5
    }
    "legendary":{
        "13000":1,
        "14000":1,
        "22000":1,
        "29000":2,
        "38000":2.5,
        "60000":3,
        "84000":3.5
    }
    "nightmare":{
        "16000":1,
        "18000":1,
        "27000":1,
        "36000":2,
        "48000":2.5,
        "75000":3,
        "105000":3.5
    }
}

**Comment by Theodotosp** [comment]
"Mazalu":
{
"normal":{
"13000":1,
"70000":1,
"95000":1,
"205000":2,
"313000":2.5,
"675000":3,
"850000":3.5
}
"hard":{
"16000":1,
"88000":1,
"119000":1,
"256000":2,
"391000":2.5,
"844000":3,
"1063000":3.5
}
"legendary":{
"20000":1,
"112000":1,
"152000":1,
"328000":2,
"500000":2.5,
"1080000":3,
"136084000":3.5
}
"nightmare":{
"25000":1,
"1408000":1,
"190000":1,
"410000":2,
"625000":2.5,
"1350000":3,
"1700000":3.5
}
}

**Comment by Theodotosp** [comment]
"General Grune":
{
"normal":{
"40000":1,
"180000":1,
"300000":1,
"440000":2,
"640000":2.5,
"1300000":3,
"1800000":3.5
}
"hard":{
"50000":1,
"225000":1,
"375000":1,
"550000":2,
"800000":2.5,
"1625000":3,
"2250000":3.5
}
"legendary":{
"64000":1,
"288000":1,
"480000":1,
"704000":2,
"1024000":2.5,
"2080000":3,
"2880000":3.5
}
"nightmare":{
"80000":1,
"360000":1,
"600000":1,
"880000":2,
"1280000":2.5,
"2600000":3,
"3600000":3.5
}
}

**Comment by Theodotosp** [comment]
"Ataxes":
{
"normal":{
"105000":1,
"120000":1,
"180000":1,
"240000":2,
"320000":2.5,
"500000":3,
"700000":3.5
}
"hard":{
"131000":1,
"150000":1,
"225000":1,
"300000":2,
"400000":2.5,
"625000":3,
"875000":3.5
}
"legendary":{
"168000":1,
"192000":1,
"288000":1,
"384000":2,
"512000":2.5,
"800000":3,
"1120000":3.5
}
"nightmare":{
"210000":1,
"240000":1,
"360000":1,
"480000":2,
"640000":2.5,
"1000000":3,
"1400000":3.5
}
}

**Comment by Theodotosp** [comment]
"Bloody Alice":
{
"normal":{
"38000":1,
"210000":1,
"285000":1,
"615000":2,
"938000":2.5,
"2025000":3,
"2550000":3.5
}
"hard":{
"47000":1,
"263000":1,
"356000":1,
"769000":2,
"1172000":2.5,
"2531000":3,
"3188000":3.5
}
"legendary":{
"60000":1,
"336000":1,
"456000":1,
"984000":2,
"1500000":2.5,
"3240000":3,
"4080000":3.5
}
"nightmare":{
"70000":1,
"420000":1,
"570000":1,
"1230000":2,
"1875000":2.5,
"4050000":3,
"5100000":3.5
}
}

**Comment by Theodotosp** [comment]
"Lurking Horror":
{
"normal":{
"70000":1,
"315000":1,
"525000":1,
"770000":2,
"1120000":2.5,
"2275000":3,
"3150000":3.5
}
"hard":{
"88000":1,
"394000":1,
"656000":1,
"963000":2,
"1400000":2.5,
"2844100":3,
"3938000":3.5
}
"legendary":{
"112000":1,
"504000":1,
"840000":1,
"1232000":2,
"1792000":2.5,
"3640000":3,
"5040000":3.5
}
"nightmare":{
"140000":1,
"630000":1,
"1050000":1,
"1540000":2,
"2240000":2.5,
"4550000":3,
"6300000":3.5
}
}

**Comment by Theodotosp** [comment]
"Briareus the Butcher":
{
"normal":{
"263000":1,
"300000":1,
"450000":1,
"600000":2,
"800000":2.5,
"1250000":3,
"1750000":3.5
}
"hard":{
"315000":1,
"360000":1,
"540000":1,
"720000":2,
"960000":2.5,
"1500000":3,
"2100000":3.5
}
"legendary":{
"368000":1,
"420000":1,
"630000":1,
"840000":2,
"1120000":2.5,
"1750000":3,
"2450000":3.5
}
"nightmare":{
"473000":1,
"540000":1,
"810000":1,
"1080000":2,
"1440000":2.5,
"2250000":3,
"3150000":3.5
}
}

**Comment by Theodotosp** [comment]
"Scylla":
{
"normal":{
"63000":1,
"350000":1,
"475000":1,
"1025000":2,
"1563000":2.5,
"3375000":3,
"4250000":3.5
}
"hard":{
"78000":1,
"438000":1,
"594000":1,
"1281000":2,
"1953000":2.5,
"4219000":3,
"5313000":3.5
}
"legendary":{
"100000":1,
"560000":1,
"760000":1,
"1640000":2,
"2500000":2.5,
"5400000":3,
"6800000":3.5
}
"nightmare":{
"125000":1,
"700000":1,
"950000":1,
"2050000":2,
"3125000":2.5,
"6750000":3,
"8500000":3.5
}
}

**Comment by Theodotosp** [comment]
Edit: moved all content to related branch

**Comment by Idrinth** [comment]
moved the stuff you already had to your folder, @Theodotosp :) ty for helping

**Comment by Theodotosp** [comment]
What programm do you use and the files get the extension .json

**Comment by Idrinth** [comment]
you can just write the name with that extension here. Otherwise JSOn is a format widely used, personally I use netbeans, but for json only that is overkill.
Maybe try sublime text 2 - it's free. https://www.sublimetext.com/

**Comment by Theodotosp** [comment]
great tool.i used to work with dreamweaver

**Comment by Idrinth** [comment]
sadly that really produces broken results - the browser might fix it, but that was never guaranteed :/

**Comment by Idrinth** [comment]
@Theodotosp added some overlooked data from mutik's - does need to be reorgered tho. Also the tiers should be applied from now on.

**Comment by Idrinth** [comment]
@Theodotosp https://dotd.idrinth.de/static/missing-tiers/ might be helpful, shows bosses without any tiers - updates once your tiers are added to the main branch(i.e. when they get activated)

**Comment by Idrinth** [comment]
@Theodotosp @Warric could you have another look at the elite balor? the tiers look way, way too low

**Comment by Idrinth** [comment]
A few more sources: 
- https://docs.google.com/spreadsheets/d/10a8qCq5zgyR-kAOq-kuKuttADfU16aVWxgTCf9Eu4b8/edit?pli=1#gid=1060618023
- https://docs.google.com/spreadsheets/d/1Zgv90jaHZCSEvpYdG5BF42djCEcgPxjEdCwosQRTbIQ/edit#gid=1169689059
- http://leon.dx.am/pages/raid_ranges.htm

**Comment by Theodotosp** [comment]
I took the tiers for this particular raid from the forum http://www.dawnofthedragons.com.
here is the page for the elites. http://www.dawnofthedragons.com/forums/forums/showthread.php?48010-Elite-Raid-Tiers

I think that maybe the sp gained that i wrote in the file maybe is confusing you Idrinth?

**Comment by Idrinth** [comment]
I think you might just have added too few zeroes to the damage tbh, @Theodotosp  
![eb](https://cloud.githubusercontent.com/assets/7874631/19150991/678ce574-8bca-11e6-892b-60540de73944.png)

**Comment by Theodotosp** [comment]
i have created the tier files for lunatics and agony,since they appear in the missing-tiers file :/
and another thing is that the WR Echthrocity appears in this file :/

**Comment by Idrinth** [comment]
echtrocity doesn't follow any usual rules - it has health, it has less than 90000 possible members and I got two of it :/
Shouldn't turn up anymore

**Comment by Idrinth** [comment]
@Theodotosp 
Lunatics [Lunatics].json
Jershan'thurn's Portal [Jershan'thurn].json
Lord Hoton the Usurper [Lord Hoton].json
Unholy Rite [Unholy Rite].json
Hullbore Wyrms [Hullbore Wyrms].json
Beastman Stampede [Stampede].json
Lost [Lost].json

all seem to be broken - misscounted closing brackets, see: https://jsonformatter.curiousconcept.com/

**Comment by Idrinth** [comment]
moved to https://github.com/IDotD/Raid-Tiers/issues/1
