### ISSUE TITLE
Add type to tierlist in RC

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#149]
Theodotos was asking for an additional piece of information displayed next to the raid tiers.

This is not yet handled by the server, but can be easily added.

**Comment by Theodotosp** [comment]
![example](https://cloud.githubusercontent.com/assets/22475199/19351240/9b71d4c8-9163-11e6-8c70-c50c67ba20eb.jpg)

**Comment by Idrinth** [comment]
Server-Side done, added data to wiki

**Comment by Idrinth** [comment]
@Ardenian @Algareb might be something for either of you - please only pick it if you got the time :)

**Comment by Ardenian** [comment]
![ticket 149 showcase](https://cloud.githubusercontent.com/assets/22526933/19437662/abc2f40e-9476-11e6-9fae-208c0ade8c6a.PNG)

Sorry for the delay, added it, now waiting for Pull Request.

**Comment by Theodotosp** [comment]
Great job @Ardenian 👍

**Comment by Ardenian** [comment]
Thanks, I can't take the credit all alone, @Idrinth helped me a lot with it, correcting my mistakes
