### ISSUE TITLE
Translated interface

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#153]
I'm wondering if we should/could add translations for the interface.

That would provide texts in the browser's language where possible and could be handled similar to the tier-data, that theo is currently collecting.

**Comment by w20k** [comment]
Actually good idea ;) I could provide translation for Russian (mb Estonian/Latvian - if needed).

**Comment by Idrinth** [comment]
would just add any language we can if that's possible :) might need to remember some french to do that :D 
i think this is mostly a followup to your #52

**Comment by Theodotosp** [comment]
I could provide translation for greek

**Comment by Ardenian** [comment]
I could contribute French.

**Comment by Algareb** [comment]
I could contribute Latin :P

**Comment by Idrinth** [comment]
Latin could be fun, would require a new setting, but that's not a real issue

**Comment by Idrinth** [comment]
feel free to add your translations to the translation folder - just reorganising some things, will provide an example as well then

**Comment by w20k** [comment]
We need to move all English translations there, as an example :)

**Comment by Idrinth** [comment]
do we really want to force another requests on the default-users(language wise)?
This would require us to do translations for all languages at the same time - so someone dropping out or being ill would prevent adding any new label.

**Comment by w20k** [comment]
Sorry for misleading you. Was thinking that there should be a base structure, which is made on top of English texts like -> default.json. So, contributors would easily just copy it to other file and translate.

**Comment by Theodotosp** [comment]
i agree with w20k, because that way will be much easier for me for example to do the translation in greek.

**Comment by Idrinth** [comment]
moved to https://github.com/IDotD/Translations/issues
