### ISSUE TITLE
Create short Script Documentation(feature|usage)

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#155]
Write short documentation about how to use the script and what it could do. Very useful for a newcomers ;)

**Comment by Idrinth** [comment]
might be related to #128 - I assume you'd want to place this in the readme?

**Comment by w20k** [comment]
Yeah, sounds good! Could be a starting point for all newcomers.

**Comment by Idrinth** [comment]
I'm not sure if #168 was sufficient, @w20k , if yes, would you close this? Otherwise give me a hit what I'd need to add :)

**Comment by w20k** [comment]
@Idrinth , I was thinking, if you could describe each functionality separately. 
Like - Settings tab contains number of dfiferent settings (list of setting), when  minimize checkbox enabled will decrease space used by the script on the screen and could be accessible via pressing on the small button .

@Idrinth , remember you had an idea about initial tutorial? We could move this "manual" to an about page or help page (which could be added) in script, or add question mark in each tab, somewhere, which will provide a short info.

**Comment by Idrinth** [comment]
would want to move your first point to #128 - just way too big to be put all of that into the readme imo.

Regarding the second one, that would make sense, but I think we should do this in another ticket and after the translation feature has been implemented. Would you open one?

**Comment by w20k** [comment]
Sure thing, will be closing this one than.
