### ISSUE TITLE
Should we make Slack(or sth. similar) required?

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#156]
I think it would be useful, in any case we'd need people to show up once in a while - not sure if all of you can?
@w20k @Algareb @Theodotosp @Ardenian

**Comment by w20k** [comment]
Could be something different, but Slack could work :)

Currently, not very active pusher, but trying to get things done with design and tests right now. Lots of work before Xmas ;)

**Comment by Idrinth** [comment]
@Algareb is in a similar boat - just ended up with a big amount of extra work, that noone planned for.

I'm open for ideas btw, if anyone wants an invitation to slack, send me a mail to webmaster AT idrinth DOT de for now and I'll do the invitations.

**Comment by Theodotosp** [comment]
OK, I agree with that idea. The platform that is better to be used i live to you, because i dont have so much knowledge.

**Comment by Algareb** [comment]
Fine for me, could be helpful for the team members that need help with the issues.

**Comment by Idrinth** [comment]
I guess it's official now, so I'll just close the issue :)
