### ISSUE TITLE
Should we add tags for expected effort/time for completion?

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#162]
Like:
- short time(minutes)
- medium time(single digit hours)
- long time(everything above)

might make it easier to find a task, that you can do with the time you have at that moment. We could also abuse milestones for that, it's just grouping after all.

**Comment by Ardenian** [comment]
I second the idea, sounds like a good idea, especially for the people still learning, as it allows to quickly sort off tickets of greater difficulty.

**Comment by w20k** [comment]
I'm not sure it's a good idea. Have to major points for that, here you go:
1. Everyone has it's own pace. I could say it's an easy task that could be done in one an hour, but for a newbie or programmer with less experience, it would take day or more. Would be better to add tags with level of complexity (easy, normal, hard or any other), that would give a better picture over tasks in general for those who is just start digging in and for all other.
2. Second thing, we're trying to make this script faster, better, stronger, and with unicorns (just joking)!!! Jokes aside, there should be a better code, better UI and etc, not number of closed issues ;) We're not in a rush - you know. Only critical or blocker tasks could be you number one priority and time consuming :)

**Comment by Idrinth** [comment]
regarding 1:
Obviously the pace differs, similar to difficulties this would be a hint to look closer if you are guessing at a completely different amount of effort needed. I don't really care if we label them one or the other, the effect should be similar.
regarding 2:
I was thinking more about being able to finish something, before there is an expected lack of time - vacation for example. I couldn't care less how fast tickets are solved(if they aren't bugs).
What it was meant to prevent is having a prerequisite just waiting for a month or two because of something forseeable ;)

**Comment by Ardenian** [comment]
Well, a general complexity tag, considering as well time and difficulty ( read into code, change code level), should do the job. Though combining it with a rough time tag cold be nice, too. Yes, people are on different levels in different areas, but I'd say one can roughly estimate the time cost. Combined with some kind of difficulty or complexity information it should be appropriate and informative.

**Comment by Idrinth** [comment]
so what about:
Low Effort expected
Medium Effort expected
High Effort expected

would that work for everyone?

**Comment by Ardenian** [comment]
Would be fine for me. In addition to the current category tags it should offer a decent overview to the required effort.

**Comment by w20k** [comment]
Sounds good!
I'm not a big fan of Agile methodology, you might got it already :)

**Comment by Idrinth** [comment]
There's a huge difference between what Agile was meant to be and what it is used as - but well, I'm not going to introduce code sprints in any case :P

**Comment by w20k** [comment]
WaterAgile - is one of the best practises, in my previous company :D Best from waterfall and agile => wateragile monster was born :) Using his super powers he destroyed my brain cells!

**Comment by Idrinth** [comment]
I think we're done with this one :)
