### ISSUE TITLE
Saving settings

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#176]
> 15:15:39Keyki:some things in your scripts don't seem to save. is that known/intended?
> 15:16:05Keyki:like the raid filters, the notification settings

Sounds like a general issue with stuff not on the top level, could you have a look, @w20k ? Otherwise I'll do that later

**Comment by Idrinth** [comment]
can't seem to replicate this in chrome.
Note to self: ask Keyki about the browser used

**Comment by w20k** [comment]
@Idrinth , Sorry, haven't been home, yet ;)

Ask Keyki about browser & version of browser, might be outdated version.

Couldn't reproduce this issue as well? Maybe Keyki was talking about something else, not settings tab?

**Comment by Idrinth** [comment]
@w20k no need to be sorry, I'm not paying you for doing 24h-support :D will try to find out more.

**Comment by Idrinth** [comment]
> 18:39:22Keyki:hi idrinth. I see you were discussing my issue. some more information: I am using chrome Version 53.0.2785.143 m
> 18:39:37Keyki:script is now at 21.0.0
> 18:40:17Keyki:what I do: go to settings, disable notifications for chat message and raid
> 18:40:48Keyki:go to raids tab, check disable for e balor, e kane and djinn
> 18:41:21Keyki:go to actions tab and reload script. all of the above mentioned settings have now reset

so more likely an issue with displaying it I assume, will check tomorrow

**Comment by Idrinth** [comment]
> (17:32) K2 Keyki: ehm, checking raids to disable auto-joining them still doesn't save the checks

so going to look for the next issue :/
