### ISSUE TITLE
Land Calculation

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#180]
In the current version the land calculation does not calculate at all.
![lb](https://cloud.githubusercontent.com/assets/7874631/19184870/63093dc6-8c7f-11e6-9ac0-340f4beb519a.png)

**Comment by Idrinth** [comment]
@w20k could you have a look?

**Comment by w20k** [comment]
@Idrinth , sure thing!

**Comment by w20k** [comment]
@Idrinth , found the cause, will fix it on weekends ;)
