### ISSUE TITLE
No direct references to settings

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#191]
Make sure, that settings are only adressed via methods, so that changing structures gets easier.
- change for modifications
- get for retrieving information

This would allow making the save method private as well.

**Comment by Ardenian** [comment]
Went through everything and replaced, as demanded by the ticket. Requires in-deep check @Idrinth for each replacement, I likely replaced complex ones faulty.

**Comment by Idrinth** [comment]
did you test if your branch still works, @Ardenian ?

**Comment by Ardenian** [comment]
It does not, @Idrinth, therefore I assume something has to be wrong.

**Comment by Idrinth** [comment]
have a look at your seperator, does it match the one in the getter?
src/mods/chat.js lines 316 and src/mods/land.js 10 use different ones

**Comment by Ardenian** [comment]
That's one part of the medal, the other one is most likely in tier.js lines 96+, pretty sure I messed up the array stuff
