### ISSUE TITLE
(Re)Loading less risky

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#194]
Currently there is not backup-plan if loading or reloading fails at first try.

**Comment by w20k** [comment]
Wanted to ask, is this option "reload", even used by users?

**Comment by Idrinth** [comment]
from time to time, yes, same reason we do - update the script when a version was changed.
In general I'm more worried about the loading part, seems to have failed for some persons and then there's no retry or similar provided by our code.

**Comment by w20k** [comment]
@Idrinth maybe it would be better option to discard this functionality?

**Comment by Idrinth** [comment]
since it does happen as well with the initial loading, I don't think reloading is the issue here

**Comment by w20k** [comment]
Do we isolate the scope on  script initializing? Do we stop all events/loops/and etc when script is terminated?

**Comment by Idrinth** [comment]
currently the events loops etc. are not terminated, just the gui and object removed(and I think a few timeouts)
