### ISSUE TITLE
Css simplification

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#195]
Wrap all displayed elements in a single wrapper div with an id, so that we have an easier time being more specific than the site's rules.
Also adjust the scss to make sure it profits from that change.

**Comment by Idrinth** [comment]
@Ardenian would you be interesting in and willing to work on this?

**Comment by Ardenian** [comment]
It sounds a tad heavy, from my perspective. I am going to read it up and decide then.

**Comment by w20k** [comment]
You could look at the BEM css methodology (http://getbem.com/introduction/).

**Comment by Idrinth** [comment]
I think the required renaming is a slight step too far for now and should be a ticket of it's own, I am more concerned about reducing issues with [Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) .

BEM is not an option, it just needlessly makes css harder to understand by splitting apart structures and forcing them all to be put at top-level. From what it does it is similar to defining every method and property we have as idrinth_{module}_{name} and filling up the global space with it.
What I do agree on is sensible naming, if there are classes or ids that we didn't name well so far, I do support sensible adjustments to their names.

**Comment by Ardenian** [comment]
I am going to give it a try, but not promising to finish it any time soon, as final exams coming close in a couple of weeks
