### ISSUE TITLE
Name gathering(Kong)

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#196]
Currently the page is effectively checked on an interval if there are any new names and those are send to the server.
It might be beneficial if we could instead use https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver instead to reduce the unnecessary re-evaluations done.

**Comment by Idrinth** [comment]
@w20k would you agree that this is useful? Might work well with the raidgathering as well #160

**Comment by w20k** [comment]
@Idrinth , I agree, it'd be a quite useful to remove intervals and replace it with MutationObservers ;)
