### ISSUE TITLE
Chat (login) window

### ISSUE THREAD

**Issue by Ardenian** [Idrinth/IDotD#206]
While debugging using the Firefox tools I noticed the chat window, at least the login window, gets re-sized and dragged under the influence of sizing the Firefox Console ( possibly related to anchoring, after my Unity experience). 
In my opinion, it is worth dicussing whether one would prefer a static size, with a scroll bar. 

![sizing](https://cloud.githubusercontent.com/assets/22526933/19287666/003e762a-9003-11e6-80b8-b6696a2b089e.PNG)

Also, one can press the 'Quests' button from AG through the chat window, just wanted to mention that, might lead to some unfortunate misclicks. This only occurs when the Chat window is somehow re-sized, as described above. 

![sizing2](https://cloud.githubusercontent.com/assets/22526933/19287857/c65eeef2-9003-11e6-9a84-cb556f66da6b.PNG)

**Comment by Idrinth** [comment]
AG is pretty annoying with their styling, agreed :/

**Comment by Idrinth** [comment]
@Ardenian the issue with quests should be solved by now, I adjusted the z-index of all elements.

**Comment by Ardenian** [comment]
Yes, it is fixed now, great job 👍 One cannot click the quest under it anymore and it has a fixed size, not changing it with the console
