### ISSUE TITLE
Dragable chat window

### ISSUE THREAD

**Issue by Ardenian** [Idrinth/IDotD#211]
Making the chat window a dragable component could greatly improve its usability. As many users nowadays have more than one screen, they could even move the chat window to a position where it does not interfer with the game. 

Requires Issue #206 to be solved.

**Comment by Idrinth** [comment]
for multiple screen purposes you'd need to strech your broser to cover them - likely placing your game right where the screens touch. I don't think that is something useful for websites tbh.

Dragable might be an option out of other reasons tho, but for now I'd stick to general options of positioning the parts.

**Comment by Ardenian** [comment]
I see, sounds reasonable, going to close this issue then for now.
