### ISSUE TITLE
Split tier-rewards

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#214]
Provide the ability to store different tier-rewards server side:
- common
- uncommon
- legendary
- epic
- direct sp

@Theodotosp not yet sure how the layout of the tier-data will be then

**Comment by Theodotosp** [comment]
as soon as you find out how they will be stored we will make the nesseccary changes. :)

**Comment by Idrinth** [comment]
ok, where there is a tier now, what about:

```
"100000": {
    "epic": 9,
    "legendary": null,
    "uncommon": null,
    "common": null,
    "stats": 800
}
```

with null being used where it's unknown.

**Comment by Idrinth** [comment]
Added it for the processing of tier-files, so you can switch at any time. Sorry about the extra work , @Theodotosp :(
Displaying the data is not yet done.

**Comment by Theodotosp** [comment]
Oh, a lot more data to write to the file. Because we split the "loot" to epic, legendary, common etc. Dont have problem adding the extra variables but not sure if i can find for all the raids this kind of information.

**Comment by Theodotosp** [comment]
I will finish firstly all the raids,so that they all display data and then i will start adding extra data, OK?

**Comment by Idrinth** [comment]
if you don't find that information just make it null :) could you move to the new format in any case?

**Comment by Theodotosp** [comment]
of course,the ones that i will create from now on will be with the new format. Is there something else that we should add? THe raid type for example is something that you can take from kong, or should we add it to the tiers file?

**Comment by Idrinth** [comment]
the raid type data is already in :) Ardenian is just not yet done with the userscript to handle that information.

**Comment by Theodotosp** [comment]
The stat variable stands for?

**Comment by Idrinth** [comment]
direct stat points

**Comment by Theodotosp** [comment]
if i got it right it is for elites and deadlies where you gain also sp?

**Comment by Idrinth** [comment]
yes, or red snows and jorms that have some at the higher tiers

**Comment by Theodotosp** [comment]
ok, creating one file so that you can tell me if it is right. :)

**Comment by Idrinth** [comment]
the file looks fine, just reformatted it a bit :)

**Comment by Theodotosp** [comment]
Id, can i ask, if i dont write to the epic variable the whole loot and i split the tiers to epic,leg,unc and common our script will unit them?or this is a project that is going to take place in the future?

**Comment by Idrinth** [comment]
It will currently only store the values. I didn't find time yet to do anything about displaying the data. It currently unites epics and stats to get the currently displayed value.

I don't understand what you don't want to write down.

**Comment by Theodotosp** [comment]
I didnt say that i dont want to write something :) I mean if the total loot is for example 100, now i write "50000000":{
            "epic": 100,
            "legendary": null,
            "uncommon": null,
            "common": null,
            "stats": null
    }

if i know that i can split the loot and write it like

"50000000":{
            "epic": 3,
            "legendary": 7,
            "uncommon": 38,
            "common": 52,
            "stats": null
    }

in the script it will show us again the total amount of loot "100"?

**Comment by Idrinth** [comment]
the first would currently say 100, the second 3.

**Comment by Theodotosp** [comment]
Could we add the picture from "lost" raid? The tiers for this raid have been uploaded, only the picture is missing. Thanks guys.

**Comment by Idrinth** [comment]
fixed, made a mistake with a calculation, x%3 is never 3 after all... :D

**Comment by Idrinth** [comment]
moved to https://github.com/IDotD/Raid-Tiers/issues/2
