### ISSUE TITLE
Chat-Registrations

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#217]
Test registration for chat.
Does it work, is it unclear anywhere?

**Comment by Idrinth** [comment]
@IDotD/base anyone here who isn't registered? should just take 2-3 mins to test this

**Comment by Ardenian** [comment]
I think I registered an aeon of time ago, but forgot everything related to it. I actually had it on the plan a couple of times, already having some note written down to it. I am going to write more after a detailled testing.

**Comment by Ardenian** [comment]
There are two main issues I noticed when messing around with the buttons: 
![chatregistration](https://cloud.githubusercontent.com/assets/22526933/22206175/7a46bfc2-e17a-11e6-8816-1071d0985de3.PNG)

1. The chat window overlaps common information boxes, requiring one to close the chat window, closing the information box and then open the chat window again. It might be a good idea to display them in front of the chat window so people are actually aware of them. Saw them only after a couple of minutes. 

2. A more severe problem, information boxes of all kinds are spawned multiple times. You can see it in the screenshot on the lefthand site. Spawning one box of a kind and checking if it is still open when it should be spawned again might be a better approach.

As for registering itself, I feel as if information regarding data persistence and how to get back lost information could be helpful. What if I forget my password, what happens to chat-rooms I never log into again ( will they persist through time ?) and what should I do regarding registering multiple times, as example what should I do when I forget my information I registered with. Such questions feel unanswered to me, what do you think, @Idrinth ?

**Comment by Idrinth** [comment]
> What if I forget my password

You'd need a new account - or I'd need to require an email to be used for registration so a new password can be send.

> what happens to chat-rooms I never log into again ( will they persist through time ?)

yes

> and what should I do regarding registering multiple times, as example what should I do when I forget my information I registered with.

I'm not sure what issue you see here

**Comment by Idrinth** [comment]
nothing to do I guess :)
