### ISSUE TITLE
AG reports script doesn't load

### ISSUE THREAD

**Issue by Ardenian** [Idrinth/IDotD#223]
Users reported the script does not show up and I myself cannot access the website ( infinite loading, maintenance ?). 

Firefxox debugger gives:
`:              rs=ACT90oEp808Px9EOdGngec_S0BtKqPLaAg:618`

**Comment by Idrinth** [comment]
There was a maintenance by my hoster today, that I didn't See before it happened. The Server should be back by now in any case.
