### ISSUE TITLE
Suggested edits to manual

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#226]
> Spelling error: avaible should be spelled available
> Under “where do i find it now”: you will need to load the site it’s going to be used on. If it’s already open, you'll need to reload it; otherwise, you should be ready to go.

**Comment by Ardenian** [comment]
Fixed, three of them, @Idrinth

**Comment by Ardenian** [comment]
There are more small things to correct, shall I hunt them down ?
Like:
- facebook, armorgames and kongregate-> Facebook, Armorgames and Kongregate 
- mutik(thank you) -> mutik ( thank you)

Mostly only nit-picking stuff, but could improve the polishness.

**Comment by Idrinth** [comment]
sure, feel free :) just haven't had time

**Comment by Ardenian** [comment]
Should be fine now, though I saw #128 should have some priority
