### ISSUE TITLE
Attack-Defense-Perception-Ratio Calculator for Utym, Kraken and Mirele ?

### ISSUE THREAD

**Issue by Ardenian** [Idrinth/IDotD#239]
Warric: 

> Hey, was just thinking with utym, kraken, mirele, it's a real pain to figure out what stats to add, maybe we could make a calculator for it in the script, or put it on a site? http://www.dawnofthedragons.com/forums/forums/showthread.php?51968-Attack-Defense-Perception-Ratio-with-Utym-Kraken-and-Mirele

**Comment by Idrinth** [comment]
I think we should remove the mounts from the calculations, I don't think they bring any new information to the calculation.
(Spreadsheet: https://docs.google.com/spreadsheets/d/1ez6xJfhUeWx7aO26_B1viD5Jzpha9UCfPm1Cv1u7gng/edit#gid=1346173974 )

**Comment by Ardenian** [comment]
Yes, I agree, focussing on the very special cases might be a good idea, mounts are covered, more or less redundant work, isn't it

**Comment by Idrinth** [comment]
the point is, that mounts just multiply the result, leaving the relative value of stats intact.

**Comment by Idrinth** [comment]
just had a look at the formulars, I think they lack a huge amount of special cases - we'll need to add to them to make sure the factors are correct
