### ISSUE TITLE
Add missing replacements for translations

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#251]
see https://github.com/IDotD/Translations/issues/2#issuecomment-272223233

**Comment by Ardenian** [comment]
Where to insert the missing ones ? Obviously, one should insert them into the language files, should one go through all and add missing fields, leaving them empty, posting in the related language issue that there are some missing ?

**Comment by Idrinth** [comment]
The point is, that some fields don't get their names requested from the translations, they seem to still be hardcoded.
English and german are the points where I'd proüose you would add the fields, every language would fall back to using english where they don't have a translation yet.

**Comment by Theodotosp** [comment]
Shouldn't we go through on translating also the popup of the raids?
http://image.prntscr.com/image/0c252f1fd29d41ffa479e5b3a27bcfc4.png

**Comment by Idrinth** [comment]
i agree with that, I think we just missed most of the less obvious cases. I forgot them for the settings-tabs as well :/
