### ISSUE TITLE
Massive performance problems of the Tiers tab

### ISSUE THREAD

**Issue by Ardenian** [Idrinth/IDotD#260]
I noticed there is quite a problem with performance when using the Tiers tab to search for tiers of a raid. When starting to enter something into the bossname field, the performance goes down to nothing. 
When the raid is found, as example entering 'horth' for Horthania, it throws 1000 and 200 error messages of type: 
`[IDotDS] TypeError: idrinth.tier[listKey] is undefined`

The first time one tries to open the tierbox of the raid ( in this example Horthania), it throws 100 errors of the same type as above and the tierbox won't show up. 
Afterwards, next tries, it will always show up properly without error message.

Entering 'horg' for Horgrak will throw lots of errors like: 
```
[IDotDS] TypeError: idrinth.tier.list[listKey].epics[difficulty] is undefined  Ardenian:1358:9
[IDotDS] TypeError: idrinth.tier[listKey] is undefined
```
and Hiorgrak won't show up as raid boss in the Tiers tab. 

When entering a single character, like 'a', the browser will freeze and Firefox will ask you eventually whether it should stop the script.

**Comment by Idrinth** [comment]
performance might be related to the way we search - guess that might need a rework

**Comment by Ardenian** [comment]
Maybe removing the auto-search on entering something into the textfield and instead adding a button to click or pressing 'enter' to activate the search will fix the performance issue.

**Comment by Idrinth** [comment]
uses the same resources, issues here is single-threads, see #265 for a solution ;)
