### ISSUE TITLE
Chat passwords

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#3]
> copy password from chat

rightclick-based menu maybe?

**Comment by Idrinth** [comment]
similar to #62 so might be better done in one go

**Comment by w20k** [comment]
Could you provide an example about usage of password copy from chat? When would users need it?

**Comment by Idrinth** [comment]
They might need it to share information in regards to chat joining to anything outside the script - for example a guild forum.
This is mostly a quality of life thing, currently they'd need to type it or visit the website to copy it.
