### ISSUE TITLE
Limit tiers search input

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#31]

**Comment by Idrinth** [comment]
in what way?

**Comment by w20k** [comment]
It should make ajax request only if input.length is more than 3 char long and doesn't contain any empty chars.

**Comment by Idrinth** [comment]
there is no ajax-request happening for the search, there's just an initial one loading the whole data.
Have a look at getTierForName that handles the search.

**Comment by w20k** [comment]
Why don't than load all the tiers, when user initilizes application?

**Comment by Idrinth** [comment]
exactly that is done:
idrinth.tier.start() makes idrinth.tier.import() store all avaible tiers once it gets a working reply from the server.

**Comment by w20k** [comment]
Found it. Thanks :)

**Comment by Idrinth** [comment]
is there still a task here?

**Comment by w20k** [comment]
Probably not, closing.
