### ISSUE TITLE
do we want auto-formatting of pullrequests?

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#317]
Was wondering if using https://github.com/prettier/prettier would be interesting for us to fix our formatting issues.
Would need to implement a service to do that i guess - haven't found any existing for it yet - that would format pullrequests.
@w20k @Ardenian

**Comment by w20k** [comment]
Yes, we do! :) Already following this project :)

**Comment by Idrinth** [comment]
you haven't seen a ready-to-use service either I assume?

**Comment by w20k** [comment]
I've used this one only, yet.
https://github.com/prettier/prettier/tree/master/editors/jetbrains

Didn't have time to configure it for our work related project.

**Comment by Idrinth** [comment]
would actually prefer it to be setup server-side as well, in best case there are just no changes

**Comment by w20k** [comment]
I agree, it would be better approach, to have an auto prettifier after every build. But haven't looked it through :)

**Comment by Idrinth** [comment]
we also need to think about when to do that automatic formatting, might be annoying (and resource-consuming) if it happens after every push

**Comment by w20k** [comment]
I think on merge would be the best option, so only when you release to master.

**Comment by Idrinth** [comment]
https://developer.github.com/webhooks/ I don't think we got that as an option tbh

**Comment by w20k** [comment]
But you could do it on this one: "release -Any time a Release is published in a Repository."

**Comment by Idrinth** [comment]
one step too late, at that point the release is already out, meaning the changes will just trigger a new release :( will have a look if I can mimic code-review/pullapprove for that - as in block the release until the whole thing is formatted properly.

**Comment by Idrinth** [comment]
https://github.com/IDotD/Userscript/pull/318 - workaround works I guess, just need to do the formatting now :D

**Comment by w20k** [comment]
Nice ;)

**Comment by Idrinth** [comment]
good thing I said not to merge :P @w20k

**Comment by w20k** [comment]
I was on a hype train, already :D My bad, sorry))

**Comment by Idrinth** [comment]
just working on getting the nodejs-part done, need to figure out how to best make that work, not quite sure how to prevent useless formatting, might need to bind that to a database entry that'll be updated.

**Comment by Idrinth** [comment]
will be switching to testing https://github.com/Idrinth/automatic-formatting - so please DO NOT merge request that are not meant to be, @w20k :P

**Comment by Idrinth** [comment]
normal versioning is re-enabled, just wanted to make sure this here doesn't cause a version jump again :D 
@IdrinthGitbot may rule^^

**Comment by w20k** [comment]
Let it loose ;)
