### ISSUE TITLE
New chat tab doesn't send msg (Chrome)

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#35]

**Comment by w20k** [comment]
Send request: Idrinth-Addition:{"maxId":"5590","messages":[{"chat":34,"text":"sdfdsfds"}]}
Got: empty {}

It seems like my demo chat is not registered on server or something else?

**Comment by Idrinth** [comment]
can actually find both the chat as well as the message in the database - will look into it

**Comment by Idrinth** [comment]
is that still happening, @w20k ?

**Comment by w20k** [comment]
Will retest it and close if it's not reproducible.

**Comment by w20k** [comment]
@Idrinth , it seems like messages are not even update in chat UI. Still reproducible ;)

**Comment by Idrinth** [comment]
will try to have a look later this week, certainly won't have a look today.

**Comment by Idrinth** [comment]
still unable to replicate this :( and there is no specific code for my user anywhere :/ @w20k Can @Ardenian replicate it?
