### ISSUE TITLE
User-Rights

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#36]
Users can currently not be promoted at all, but can be banned.
The whole related code needs to be checked.

Owners should be able to: promote to mod, promote to owner, demote to mod, demote to user, ban
Mods should be able to : ban
Users should be able to: -

**Comment by w20k** [comment]
What banned users, mods and with empty rank can do in popup options?

**Comment by Idrinth** [comment]
Banned nothing,see above for Mods and users.
Empty rank should not exist - if you're in a chat you are a User and might be promoted or kicked to another rank.

**Comment by w20k** [comment]
Could ban users be in chat room?

**Comment by Idrinth** [comment]
yes, they couldn't write or read, but in theory they could still be in atm

**Comment by w20k** [comment]
Should be fixed by now.

**Comment by Idrinth** [comment]
might just want to commit with Fixes #36 next time, but I agree

**Comment by w20k** [comment]
Ther are bug(#36), but I forgot about #45. Will be more careful next time.
