### ISSUE TITLE
not having to minimalise the chat each time i start up the game

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#38]
Toine via GoogleDocs

**Comment by Idrinth** [comment]
Have a look at
Settings -> Enable chat(needs script reload)

This should solve your issue if you're not using the chat.

**Comment by Idrinth** [comment]
Just talked to toine:
The wish is, that it may start minimized but be active, this could be added as another checkbox in the settings.

**Comment by w20k** [comment]
I think would be good to make it by default folded. And if you want in config you could override this option. 
What do you think @Idrinth ?

**Comment by Idrinth** [comment]
yes, we can switch it around.
The idea behind having it big by default is showing people that there is that chat - was done when it was introduced and never changed.
