### ISSUE TITLE
Release notes generator

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#51]
Maybe we could you release notes generator? So we could see in each release what features/bugs were closed in that version.

**Comment by Idrinth** [comment]
With the likely changes to versioning in #59 I don't think we actually need a release note generator. Might also need to redefine the milestones tbh

**Comment by Idrinth** [comment]
if I didn't break anything https://dotd.idrinth.de/kongregate/update/ will contain notes from all the future pushes to master once they're accepted

**Comment by w20k** [comment]
You rock ;) Seems like it's working, haven't tested yet.

**Comment by Idrinth** [comment]
seem to work
