### ISSUE TITLE
AP tracking

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#56]
Toine: AP tracking would be cool, but might be a bit intensive on the server and to program in general: ugup only tracks the last 5 achievos i think so:
- leaderboard for total AP gained
- and a tracker to see how many more of a specific raid you need for the next AP
- combined with a list of available raids that you re almost at AP tier of

**Comment by Idrinth** [comment]
1) nothing userscript related
2) not possible, data not avaible
3) not possible, data not avaible

**Comment by Idrinth** [comment]
What I'll add is ap-owned to profiles.

**Comment by w20k** [comment]
Nice feature ;) Looking forward!

**Comment by Idrinth** [comment]
Collecting works - at least as far as possible. Will be adding displays later today.

**Comment by Idrinth** [comment]
done as far as possible.
