### ISSUE TITLE
Merge Manual with Readme

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#58]
Having two files with nearly the same reason is not very useful, so they should be combined.

**Comment by w20k** [comment]
I think 'Manual.html' should be converted to md and added as a link to Readme file. Don't think it's a good idea to use two differnet formats html and md. 
What do you think @Idrinth ?

**Comment by Idrinth** [comment]
html was just the most sane export format that google docs provided that didn't lose information. Otherwise I would prefer md as well here.

Regarding merging or not, I think the readme won't have much left to do once the manual is a readable document.

**Comment by w20k** [comment]
I converted Manual html into md. Take a look at pull request.
