### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#59]
Since we technically have CI it might be useful to replace the currently static versions with something else that can be handled by both the caching as well as the monkeys.

**Comment by Idrinth** [comment]
Supported Versionformats: https://developer.mozilla.org/en-US/docs/Toolkit_version_format
Data avaible from github: "f766a7353fba26f5bfd072d8c8f040957447fdc0" (i.e. commit-hash)

**Comment by Idrinth** [comment]
I guess we could also just count up, as in every time it get's something pushed the version is incremented by 1, @w20k ?

**Comment by w20k** [comment]
Sound good, just add up '1'  to a build version every time master gets a new update. 
Do you update manually release version?

**Comment by Idrinth** [comment]
currently the version of the userscript is hardcoded in a static of the php-class handling the file merges, caching etc. .
I don't think releases make any sense when combined with the way the branches are already deployed, we'll just go up in version-numbers quickly like that and it might be hard to keep track of where we are atm.

**Comment by Idrinth** [comment]
Storing the data works, just adjusted it a bit so empty lines aren't stored.
Next step is creating a release automatically for that version.

**Comment by w20k** [comment]
Sounds good, looking forward ;)

**Comment by Idrinth** [comment]
https://github.com/Idrinth/github-auto-release reworking that one, it contains a lot of the needed structure, sadly it's very outdated

**Comment by Idrinth** [comment]
finished reworking that script. It's deployed and should handle releases fine now.

**Comment by w20k** [comment]
That's good 👍
