### ISSUE TITLE
Commits & Pull request flow

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#60]
@Idrinth  Could you add your comments on flow of commits/closing tickets/pull requests in general.

**Comment by Idrinth** [comment]
- commit with "Fixes #[ticket]" so the commits are automatically listed in the ticket
- test the changes yourself and fix any bugs you might encounter in your branch
- create a pull-request and (if possible) let someone have a look
- when accepting the pull-request all related tickets are closed

**Comment by Idrinth** [comment]
maybe we should add a developer-readme with that kind of information?

**Comment by w20k** [comment]
Good idea, could you add your notes to developer-readme and close this task.
