### ISSUE TITLE
Delete/Close private chat

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#62]

**Comment by Idrinth** [comment]
kick/ban all and leave should be possible already, even if self-ban doesn't exist yet. Also an option easier handled on the website atm.

**Comment by w20k** [comment]
I think it would be good idea to add 'leave' option to private none global chats.

**Comment by Idrinth** [comment]
agreed

**Comment by w20k** [comment]
One more point in here. Owner of the private tab should have an options to close chat and kick everyone out, after doing so.

**Comment by Idrinth** [comment]
Would have closed any chat without an owner tbh, but that's server-side anyway
