### ISSUE TITLE
Codestyle checks/Linter

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#65]
Refering to #55
We got a linter running with [codeclimate](https://docs.codeclimate.com/docs/list-of-engines) (eslint,csslint) as well as fixme, that looks for todo's etc.

Codacy does refer to the eslint config file in this project as well afaik, so maybe that needs to be adjusted?

Regarding IDE, I'm using netbeans

**Comment by w20k** [comment]
Do you have any preference, despite closing brackets? Number of tabs or anything else?

**Comment by Idrinth** [comment]
spaces over tabs personally, there's just too many cases where tabs get messed up - including github itself often.
Other than that enforce the ending semicolon - makes reading easier.

**Comment by w20k** [comment]
Could you export your javascript styles from NetBeans to a file? :)

**Comment by Idrinth** [comment]
export seems to be broken with the version I got - or it just doesn't export defaults. I hope the json helps, took me a while to type :D
[netbeans formatting settings.json.txt](https://github.com/Idrinth/IDotD/files/380222/netbeans.formatting.settings.json.txt)

**Comment by w20k** [comment]
Have you used Node.JS? It's related to task #84.

**Comment by Idrinth** [comment]
don't usually see a benefit in it - got little need to bring a language I dislike for a lot of reasons into a second enviroment.
In any case setting up Node.JS shouldn't be much of an issue.

**Comment by Idrinth** [comment]
regarding nodejs, how would you like to supply the tests to run? we'd need to setup an automated run after every push I guess, so we need to define a structure :)

**Comment by w20k** [comment]
Could you take a look if codacy could run tests? I have already did minor preparations.

I agree, eveytime you push your changes tests are run on the CI side or we could run test only on pull request. Like code lint right now? What do you think? :)

**Comment by Idrinth** [comment]
I would test on all pushes - makes sure we find issues even before pulling to the master.

Regarding codacy(and codeclimate): they don't seem to run tests, but they can display the coverage, when provided by a third(fourth) party tool. Might be useful but not quite what we'd need right now.

**Comment by w20k** [comment]
Than we need a simple CI to run tests and push notification to user (or email) that your tests failed on commit/push.

**Comment by Idrinth** [comment]
comment on commit maybe? Need to have a quick look at the github api, but I'm sure it'd work

**Comment by Idrinth** [comment]
yes, would work: https://developer.github.com/v3/repos/comments/#create-a-commit-comment

**Comment by w20k** [comment]
Yeah, you're right, would work :+1:

**Comment by Idrinth** [comment]
Will have a look to expand https://github.com/Idrinth/github-auto-release with the option of starting those tests(second deployment+api-call to start i guess), but will need to switch configuration first, .ini is not really qualified for that many lists with multiple levels :D

**Comment by w20k** [comment]
Yaml is a good options, too :smile_cat:

Looking forward ;) I will do some minor tests for now, after will finish with refactoring.

**Comment by Idrinth** [comment]
originally it wasn't meant for anything with many levels of options, that's why i picked ini :D 
Yaml is not part of the php-core, so json would be my choice here:
http://php.net/manual/en/function.yaml-parse.php
http://php.net/manual/en/function.json-decode.php

**Comment by w20k** [comment]
Cruel Php world! :)

**Comment by Idrinth** [comment]
nodejs v4.4.7 ok?

**Comment by w20k** [comment]
Yes, it's good!

**Comment by Idrinth** [comment]
moves styles to https://github.com/Idrinth/IDotD/wiki/Code-Formatting - feel free to adjust them

**Comment by Idrinth** [comment]
closing thise, the original topic is taken care of, the resulting job is moved to an issue of it's own.
