### ISSUE TITLE
Update clipboard.js

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#66]
https://github.com/zenorocha/clipboard.js is using a newer version of lib/clipboard.js at the moment, that would need to be tested and integrated.

**Comment by w20k** [comment]
I doesn't support Safari - Noo :)  
Do we use it often? Cliboard.js?

**Comment by Idrinth** [comment]
we use it for newgrounds, where automatic joining is impossible at the moment - they get one-click copiing there instead :/
Need to continue pushing them to add a way of properly join raids on that platform :(

**Comment by w20k** [comment]
Hmm...wouuld be better to drop that cliboard.js from the project, but if you say it's not possible at the moment. We should add test for sure, in next major. Would be easier to test things. 
Will look at it, if it's not a pain :)

**Comment by Idrinth** [comment]
if you got a replacement that's fine with me as well.
The issue is, that we need to keep it for newgrounds at the very least and #3 does need something similar as well.

**Comment by Idrinth** [comment]
I believe that the method in #109 should be sufficient for our needs actually, so that we can remove the library once it's replaced in code.

**Comment by w20k** [comment]
Should be enough, needs tests to be done.

**Comment by Idrinth** [comment]
moved the slightly changed task to #137
