### ISSUE TITLE
local Filtering of raids

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#82]
to allow for better work with 3rd party raidsources, there needs to be a simple filter for raids - by boss maybe.
This will allow:
- including raids from chat
- including raids from the event-manager

**Comment by w20k** [comment]
Do you want do add any other filters? Like by monster type or something like that? 
Example: Aqua or raid name?

**Comment by Idrinth** [comment]
would leave it at boss(i.e. raid name) for now, this is just meant to provide some very simple filtering for raids not going through the server.

**Comment by w20k** [comment]
One question: where should I get information about raids? From chat or any other source that you could specify?

**Comment by Idrinth** [comment]
would just add new (set of) lists for raids for now, will take care of filling it later - once we got an api for the above :)
