### ISSUE TITLE
Automatic testing

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#84]
I found three different frameworks for unittests in javascript, that might be useful here. All seem to need a browser, so will need to have a look on how to simulate one properly and/or how to get it's results.
https://github.com/jquery/qunit
https://github.com/jasmine/jasmine
https://github.com/mochajs/mocha/

Are either of those interesting for the unittests you did want to add, @w20k ?

**Comment by w20k** [comment]
I used all of them. 
There is an option to add phantom browser, but I will take a look if we could do it without additional overkill - like installing npm.

**Comment by Idrinth** [comment]
anyway, what framework did you prefer? Never worked with either, so...

**Comment by w20k** [comment]
Latest jasmine is mostly preferable ;)

**Comment by Idrinth** [comment]
everything else is handled in #125
