### ISSUE TITLE
remove type:div from element creation

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/IDotD#86]
since div is the default type, it might make the code a little smaller and easier to read if we remove all the type:"div" from the objects that are build.

**Comment by Idrinth** [comment]
@w20k what's your opinion on this? would it be useful for us to remove that bit?

**Comment by w20k** [comment]
I think it's a good idea to clean up a code a bit. Less characters -> more readable :).

**Comment by Idrinth** [comment]
will take care of this once deleting and leaving work :)
