### ISSUE TITLE
Describe Server API

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#88]
@Idrinth  Write down to the docs server API (calls and responses).

**Comment by Idrinth** [comment]
will do, might just take a bit

**Comment by w20k** [comment]
Thanks :+1:

**Comment by Idrinth** [comment]
is there any api-part you want me to start with?

**Comment by w20k** [comment]
Could you start with tier and chat/user.

**Comment by Idrinth** [comment]
tier: https://github.com/Idrinth/IDotD/wiki/Server-Api#tiers-service

**Comment by w20k** [comment]
Great! Thank you :) Really useful!

**Comment by Idrinth** [comment]
finished
https://github.com/Idrinth/IDotD/wiki/Server-Api#chat-service
https://github.com/Idrinth/IDotD/wiki/Server-Api#i-am-alive
https://github.com/Idrinth/IDotD/wiki/Server-Api#users-service

**Comment by Idrinth** [comment]
all done
