### ISSUE TITLE
Script is reloading incorrectly

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#91]
Could be an option to remove script reloading functionality and make it more real time experience;

(index):2411 Uncaught TypeError: Cannot read property 'messages' of undefinedrefreshChats @ (index):24112
(index):3296 Uncaught TypeError: Cannot read property 'join' of undefined(anonymous function) @ (index):3296
(index):3954 Uncaught TypeError: Cannot read property 'isWorldServer' of undefinedsendAlive @ (index):3954
(index):914 Uncaught TypeError: Cannot read property 'indexOf' of undefinedidrinth.ajax.(anonymous function)._remove @ (index):914idrinth.ajax.(anonymous function).onreadystatechange @ (index):934
(index):964 [IDotDS] Starting Idrinth's DotD Script

**Comment by Idrinth** [comment]
there's a few setTimeout that aren't properly cleaned, otherwise it should work fine :/

**Comment by w20k** [comment]
raid.join -> sometimes fail to load scrip after reload.

**Comment by w20k** [comment]
Found some strange reload behavior -> sc.setAttribute ( 'src', 'https://dotd.idrinth.de/static/userscript/' + Math.random () + '/' );
Why do you load up a new script every time user presses the button to reload script?

**Comment by Idrinth** [comment]
because loading a fresh, up to date one is actually intended - making sure they get one not cached on the client side

**Comment by w20k** [comment]
Why don't you use [cache-buster](http://curtistimson.co.uk/front-end-dev/what-is-cache-busting/) with removing previous script insertion? 
In this case script won't be cached. What do you think?

Right now, if you reload 20 times script. It will load 20 more scripts. Already tested :)

**Comment by Idrinth** [comment]
the Math.random is technically a kind of cache buster already - the old instances would need to be removed tho, agreed

**Comment by w20k** [comment]
One issue was that I had my own branch loaded as a testing version "/asdsad", and when I reloaded the script it loaded the master version instead :) It was confusing a bit.

**Comment by Idrinth** [comment]
we could move it one step back in the param-list, so:
dotd.idrinth.de/static/userscript/[version]/[RANDOM]/ , would not take any server-side adjustments to work

**Comment by w20k** [comment]
That's a good idea :) Will do so than!

**Comment by Idrinth** [comment]
###RELOAD-VERSION### might be interesting for you - makes sure you don't need to do string operations on the old script's source-url ;)

**Comment by w20k** [comment]
Have you commited it somewhere "###RELOAD-VERSION###" ? :) Can't find it within commits :)

**Comment by Idrinth** [comment]
it's a server-side replacement, same as ###VERSION###

**Comment by Idrinth** [comment]
https://github.com/Idrinth/IDotD/wiki/Developer-Information#server-side-replacements contains the (currently 3) replaced keys
