### ISSUE TITLE
Refactor Settings

### ISSUE THREAD

**Issue by w20k** [Idrinth/IDotD#96]
Would be better to save settings as a single object, istead of multiple entries.

Example:

``` javascript
localStorage.setItem( 'test', JSON.stringify(car) );
console.log( JSON.parse( localStorage.getItem( 'test' ) ) );
```

**Comment by w20k** [comment]
Will add type safe parsing;

**Comment by Idrinth** [comment]
just wondering, if you would rather do the test in #84 - might be more useful than the refactoring for now.

**Comment by Idrinth** [comment]
@w20k the last comment was meant for you - would take care of this, if you take the tests-issue (#125)

**Comment by w20k** [comment]
Sorry @Idrinth , missed that one. Too many messages from Github lately :)
Actually this task could closed, and done as a part of #138

**Comment by Idrinth** [comment]
I considered #138 to be more of a frontend topic to be honest, even if grouping settings might make sense here as well.
Did you have a look if your refactored code can still work with the changes that happened in between?

**Comment by w20k** [comment]
It should, but I'll change few thing and throw out some functions. So, it's pretty much from scratch :) But I will start from testing part #125, otherwise I will kill myself during testing of the written code!

#138 - I was thinking to do it both, like UI part and made some groups in our settings as well. Win-win :)
